[package]
name = "elf64"
version = "0.1.0"
authors = ["Ranxi Verba <ranxi.verba@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = { version = "1.3", default-features = false }
bitflags = { version = "1.2" }
